return {
	"https://github.com/nvim-treesitter/nvim-treesitter",
	version = "^0.10.0",
	event = "VeryLazy",
	build = ":TSUpdate",

	config = function()
		require("nvim-treesitter.configs").setup({
			modules = {},
			highlight = { enable = true },
			sync_install = false,
			auto_install = true,
			ignore_install = {},
			ensure_installed = {
				"bash",
				"comment",
				"css",
				"git_config",
				"gitattributes",
				"gitignore",
				"go",
				"graphql",
				"html",
				"javascript",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"lua",
				"make",
				"markdown",
				"scss",
				"typescript",
				"vim",
				"vue",
				"yaml",
				-- "gleam",
			},
		})
	end,
}
