require("nvim-treesitter.configs").setup {
  modules = {},
  sync_install = false,
  auto_install = true,
  ensure_installed = {
    "bash",
    "comment",
    "css",
    "elixir",
    "git_config",
    "gitattributes",
    "gitignore",
    "go",
    "graphql",
    "html",
    "javascript",
    "json",
    "json5",
    "jsonc",
    "lua",
    "luap",
    "make",
    "markdown",
    "scss",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  ignore_install = {},
  highlight = {
    enable = true,
  },
}
